version: "3"

services:
    nginx:
        image: nginx:1.20-alpine
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    app:
        image: laravel-vue-demo/app:latest
        build:
            context: .
            dockerfile: ./.docker/app/Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./.docker/app/init.sh:/home/init.sh
            - ./:/var/www/html
        command: /bin/bash -c "composer install && php-fpm"
        depends_on:
            - db

    frontend:
        image: node:lts
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        command: /bin/bash -c "npm install && npm run dev"
        ports:
            - "5173:5173"
        depends_on:
            - db

    db:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./.docker/mysql:/docker-entrypoint-initdb.d
            - database-data:/var/lib/mysql

volumes:
    database-data:
